Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  Enabled: false
  Include:
    - spec/
Metrics/AbcSize:
  Max: 18
Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
AllCops:
  TargetRubyVersion: 2.7
